import type { Receipt } from '../types';
import { receiptPaperDataUrl } from './receiptImage';

// Deterministic sample data seeded into localStorage on first run so the app is
// never empty. Mix of upload/email sources, all three statuses, spread across
// categories and dates. `id` values are stable strings for easy linking.

function img(vendor: string, amount: number, date: string): string {
  return receiptPaperDataUrl({ vendor, amount, date });
}

export function buildSeedReceipts(): Receipt[] {
  return [
    {
      id: 'rcpt-delta-001',
      imageUrl: img('Delta Air Lines', 428.6, '2026-07-12'),
      vendor: 'Delta Air Lines',
      amount: 428.6,
      currency: 'USD',
      date: '2026-07-12',
      category: 'Travel',
      taxAmount: 32.14,
      source: 'email',
      status: 'needs_review',
      createdAt: '2026-07-12T15:20:00.000Z',
      emailFrom: 'receipts@delta.com',
      emailSubject: 'Your flight receipt — LGA to SFO',
      uncertainField: 'amount',
    },
    {
      id: 'rcpt-bluebottle-002',
      imageUrl: img('Blue Bottle Coffee', 14.75, '2026-07-11'),
      vendor: 'Blue Bottle Coffee',
      amount: 14.75,
      currency: 'USD',
      date: '2026-07-11',
      category: 'Meals',
      taxAmount: 1.21,
      source: 'upload',
      status: 'confirmed',
      createdAt: '2026-07-11T17:45:00.000Z',
      uncertainField: null,
    },
    {
      id: 'rcpt-figma-003',
      imageUrl: img('Figma', 45.0, '2026-07-10'),
      vendor: 'Figma',
      amount: 45.0,
      currency: 'USD',
      date: '2026-07-10',
      category: 'Software',
      taxAmount: null,
      source: 'email',
      status: 'confirmed',
      createdAt: '2026-07-10T08:02:00.000Z',
      emailFrom: 'billing@figma.com',
      emailSubject: 'Figma receipt — Professional monthly plan',
      uncertainField: null,
    },
    {
      id: 'rcpt-officedepot-004',
      imageUrl: img('Office Depot', 86.13, '2026-07-09'),
      vendor: 'Office Depot',
      amount: 86.13,
      currency: 'USD',
      date: '2026-07-09',
      category: 'Office Supplies',
      taxAmount: 7.66,
      source: 'upload',
      status: 'needs_review',
      createdAt: '2026-07-09T14:41:00.000Z',
      uncertainField: 'amount',
    },
    {
      id: 'rcpt-verizon-005',
      imageUrl: img('Verizon', 92.4, '2026-07-05'),
      vendor: 'Verizon',
      amount: 92.4,
      currency: 'USD',
      date: '2026-07-05',
      category: 'Utilities',
      taxAmount: 6.83,
      source: 'email',
      status: 'confirmed',
      createdAt: '2026-07-05T11:15:00.000Z',
      emailFrom: 'no-reply@verizon.com',
      emailSubject: 'Your Verizon bill is ready — business line',
      uncertainField: null,
    },
    {
      id: 'rcpt-uber-006',
      imageUrl: img('Uber', 23.18, '2026-07-03'),
      vendor: 'Uber',
      amount: 23.18,
      currency: 'USD',
      date: '2026-07-03',
      category: 'Travel',
      taxAmount: null,
      source: 'upload',
      status: 'confirmed',
      createdAt: '2026-07-03T20:10:00.000Z',
      uncertainField: null,
    },
    {
      id: 'rcpt-notion-007',
      imageUrl: img('Notion Labs', 20.0, '2026-07-02'),
      vendor: 'Notion Labs',
      amount: 20.0,
      currency: 'USD',
      date: '2026-07-02',
      category: 'Software',
      taxAmount: null,
      source: 'email',
      status: 'confirmed',
      createdAt: '2026-07-02T06:30:00.000Z',
      emailFrom: 'team@notion.so',
      emailSubject: 'Receipt from Notion — Plus plan',
      uncertainField: null,
    },
    {
      id: 'rcpt-shell-008',
      imageUrl: img('Shell', 61.42, '2026-06-28'),
      vendor: 'Shell',
      amount: 61.42,
      currency: 'USD',
      date: '2026-06-28',
      category: 'Travel',
      taxAmount: null,
      source: 'upload',
      status: 'confirmed',
      createdAt: '2026-06-28T13:05:00.000Z',
      uncertainField: null,
    },
    {
      id: 'rcpt-chipotle-009',
      imageUrl: img('Chipotle', 18.9, '2026-06-25'),
      vendor: 'Chipotle',
      amount: 18.9,
      currency: 'USD',
      date: '2026-06-25',
      category: 'Meals',
      taxAmount: 1.55,
      source: 'upload',
      status: 'confirmed',
      createdAt: '2026-06-25T19:22:00.000Z',
      uncertainField: null,
    },
    {
      id: 'rcpt-comcast-010',
      imageUrl: img('Comcast Business', 129.99, '2026-06-20'),
      vendor: 'Comcast Business',
      amount: 129.99,
      currency: 'USD',
      date: '2026-06-20',
      category: 'Utilities',
      taxAmount: 9.75,
      source: 'email',
      status: 'confirmed',
      createdAt: '2026-06-20T09:00:00.000Z',
      emailFrom: 'billing@comcastbusiness.com',
      emailSubject: 'Your monthly statement is available',
      uncertainField: null,
    },
    {
      id: 'rcpt-staples-011',
      imageUrl: img('Staples', 42.37, '2026-06-15'),
      vendor: 'Staples',
      amount: 42.37,
      currency: 'USD',
      date: '2026-06-15',
      category: 'Office Supplies',
      taxAmount: 3.36,
      source: 'upload',
      status: 'confirmed',
      createdAt: '2026-06-15T15:40:00.000Z',
      uncertainField: null,
    },
  ];
}
